/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/
module

public import Mathlib.RingTheory.MvPolynomial.Ideal
public import Mathlib.RingTheory.Nullstellensatz

/-!
# Coordinate differences and evaluation ideals

The ideal generated by the differences `X i - C (x i)` is the kernel of
evaluation at `x`. Membership is therefore characterized by vanishing at `x`.
Over a field this ideal also agrees with the singleton `vanishingIdeal`.
-/

@[expose] public section

namespace MvPolynomial

universe u v

variable {R : Type u} {σ : Type v} [CommRing R]

/-- The ideal of coordinate differences at a point is the kernel of evaluation
at that point, for arbitrary variable types and commutative coefficient rings. -/
theorem ideal_span_X_sub_C_eq_ker_eval (x : σ → R) :
    Ideal.span (Set.range (fun i : σ => X i - C (x i))) = RingHom.ker (eval x) := by
  let I : Ideal (MvPolynomial σ R) :=
    Ideal.span (Set.range (fun i : σ => X i - C (x i)))
  change I = RingHom.ker (eval x)
  apply le_antisymm
  · refine Ideal.span_le.mpr ?_
    rintro p ⟨i, rfl⟩
    simp [RingHom.mem_ker]
  · intro p hp
    have hX (i : σ) :
        Ideal.Quotient.mk I (X i) = Ideal.Quotient.mk I (C (x i)) := by
      apply (Ideal.Quotient.mk_eq_mk_iff_sub_mem (X i) (C (x i))).2
      exact Ideal.subset_span (Set.mem_range_self i)
    have h : (Ideal.Quotient.mk I) =
        ((Ideal.Quotient.mk I).comp (C : R →+* MvPolynomial σ R)).comp (eval x) := by
      apply ringHom_ext
      · intro r
        simp
      · intro i
        simpa [RingHom.comp_apply] using hX i
    apply Ideal.Quotient.eq_zero_iff_mem.mp
    rw [RingHom.congr_fun h p]
    simp [RingHom.comp_apply, RingHom.mem_ker.mp hp]

/-- A polynomial lies in the ideal of coordinate differences at `x` exactly
when it vanishes at `x`. -/
theorem mem_ideal_span_X_sub_C_iff (x : σ → R) (p : MvPolynomial σ R) :
    p ∈ Ideal.span (Set.range (fun i : σ => X i - C (x i))) ↔ eval x p = 0 := by
  rw [ideal_span_X_sub_C_eq_ker_eval, RingHom.mem_ker]

/-- Over a field, the coordinate-difference ideal agrees with the singleton
vanishing ideal. Neither algebraic closure nor finitely many variables is needed. -/
theorem ideal_span_X_sub_C_eq_vanishingIdeal_singleton
    {k : Type u} [Field k] (x : σ → k) :
    Ideal.span (Set.range (fun i : σ => X i - C (x i))) = vanishingIdeal k {x} := by
  ext p
  rw [mem_ideal_span_X_sub_C_iff, mem_vanishingIdeal_singleton_iff]
  rfl

end MvPolynomial
