/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/
module

public import Mathlib.RingTheory.MvPolynomial.Ideal
public import Mathlib.RingTheory.Nullstellensatz
public import Mathlib.Algebra.MvPolynomial.Comap
public import Mathlib.RingTheory.Spectrum.Prime.RingHom

/-!
# Coordinate differences and evaluation ideals

The ideal generated by the differences `X i - C (x i)` is the kernel of
evaluation at `x`. Membership is therefore characterized by vanishing at `x`.
Over a field this ideal also agrees with the singleton `vanishingIdeal`.
Polynomial substitution contracts evaluation kernels and coordinate-difference
ideals, and the corresponding field-valued points commute with spectrum comap.
-/

@[expose] public section

namespace MvPolynomial

universe u v

variable {R : Type u} {σ : Type v} [CommRing R]

/-- The ideal of coordinate differences at a point is the kernel of evaluation
at that point, for arbitrary variable types and commutative coefficient rings. -/
theorem ideal_span_X_sub_C_eq_ker_eval (x : σ → R) :
    Ideal.span (Set.range (fun i : σ => X i - C (x i))) = RingHom.ker (eval x) := by
  let I : Ideal (MvPolynomial σ R) :=
    Ideal.span (Set.range (fun i : σ => X i - C (x i)))
  change I = RingHom.ker (eval x)
  apply le_antisymm
  · refine Ideal.span_le.mpr ?_
    rintro p ⟨i, rfl⟩
    simp [RingHom.mem_ker]
  · intro p hp
    have hX (i : σ) :
        Ideal.Quotient.mk I (X i) = Ideal.Quotient.mk I (C (x i)) := by
      apply (Ideal.Quotient.mk_eq_mk_iff_sub_mem (X i) (C (x i))).2
      exact Ideal.subset_span (Set.mem_range_self i)
    have h : (Ideal.Quotient.mk I) =
        ((Ideal.Quotient.mk I).comp (C : R →+* MvPolynomial σ R)).comp (eval x) := by
      apply ringHom_ext
      · intro r
        simp
      · intro i
        simpa [RingHom.comp_apply] using hX i
    apply Ideal.Quotient.eq_zero_iff_mem.mp
    rw [RingHom.congr_fun h p]
    simp [RingHom.comp_apply, RingHom.mem_ker.mp hp]

/-- A polynomial lies in the ideal of coordinate differences at `x` exactly
when it vanishes at `x`. -/
theorem mem_ideal_span_X_sub_C_iff (x : σ → R) (p : MvPolynomial σ R) :
    p ∈ Ideal.span (Set.range (fun i : σ => X i - C (x i))) ↔ eval x p = 0 := by
  rw [ideal_span_X_sub_C_eq_ker_eval, RingHom.mem_ker]

/-- Over a field, the coordinate-difference ideal agrees with the singleton
vanishing ideal. Neither algebraic closure nor finitely many variables is needed. -/
theorem ideal_span_X_sub_C_eq_vanishingIdeal_singleton
    {k : Type u} [Field k] (x : σ → k) :
    Ideal.span (Set.range (fun i : σ => X i - C (x i))) = vanishingIdeal k {x} := by
  ext p
  rw [mem_ideal_span_X_sub_C_iff, mem_vanishingIdeal_singleton_iff]
  rfl

end MvPolynomial

namespace MvPolynomial

universe u v w z

variable {R : Type u} {S : Type v} {σ : Type w} {τ : Type z}
variable [CommSemiring R] [CommSemiring S] [Algebra R S]

/-- Pulling an evaluation kernel back along a polynomial algebra homomorphism
evaluates at the images of the source coordinates. The target point may take
values in a coefficient algebra. -/
theorem ker_aeval_comap (f : MvPolynomial σ R →ₐ[R] MvPolynomial τ R) (x : τ → S) :
    (RingHom.ker (aeval x).toRingHom).comap f.toRingHom =
      RingHom.ker (aeval (fun i => aeval x (f (X i)))).toRingHom := by
  rw [RingHom.comap_ker]
  change RingHom.ker (((aeval x).comp f).toRingHom) = _
  rw [aeval_unique ((aeval x).comp f)]
  rfl

end MvPolynomial

namespace MvPolynomial

universe u w z

variable {R : Type u} {σ : Type w} {τ : Type z} [CommRing R]

/-- A polynomial substitution pulls the coordinate-difference ideal back to
the coordinate-difference ideal at the substituted point. -/
theorem ideal_span_X_sub_C_comap
    (f : MvPolynomial σ R →ₐ[R] MvPolynomial τ R) (x : τ → R) :
    (Ideal.span (Set.range (fun i : τ => X i - C (x i)))).comap f.toRingHom =
      Ideal.span (Set.range (fun i : σ =>
        (X i : MvPolynomial σ R) - C (MvPolynomial.comap f x i))) := by
  rw [ideal_span_X_sub_C_eq_ker_eval, ideal_span_X_sub_C_eq_ker_eval]
  change (RingHom.ker (aeval x).toRingHom).comap f.toRingHom =
    RingHom.ker (aeval (comap f x)).toRingHom
  have hpoint : comap f x = fun i => aeval x (f (X i)) := by
    funext i
    exact comap_apply f x i
  rw [hpoint]
  exact ker_aeval_comap f x

end MvPolynomial

namespace MvPolynomial

universe u v w z

variable {k : Type u} {K : Type v} {σ : Type w} {τ : Type z}
variable [Field k] [Field K] [Algebra k K]

/-- Under polynomial substitution, contraction of the prime defined by a
field-valued point is the prime at the substituted point. -/
theorem pointToPoint_comap
    (f : MvPolynomial σ k →ₐ[k] MvPolynomial τ k) (x : τ → K) :
    PrimeSpectrum.comap f.toRingHom (pointToPoint (k := k) x) =
      pointToPoint (k := k) (fun i => aeval x (f (X i))) := by
  apply PrimeSpectrum.ext
  ext p
  change f p ∈ (vanishingIdeal k {x} : Ideal _) ↔
    p ∈ (vanishingIdeal k {fun i => aeval x (f (X i))} : Ideal _)
  have hcomp : (aeval x).comp f = aeval (fun i => aeval x (f (X i))) := by
    rw [aeval_unique ((aeval x).comp f)]
    rfl
  simpa only [mem_vanishingIdeal_singleton_iff, AlgHom.comp_apply] using
    (Iff.of_eq (congrArg (fun φ : MvPolynomial σ k →ₐ[k] K => φ p = 0) hcomp))

/-- For points valued in the coefficient field, polynomial substitution acts
on prime-spectrum points through `MvPolynomial.comap`. -/
theorem pointToPoint_comap_self
    (f : MvPolynomial σ k →ₐ[k] MvPolynomial τ k) (x : τ → k) :
    PrimeSpectrum.comap f.toRingHom (pointToPoint (k := k) x) =
      pointToPoint (k := k) (comap f x) := by
  have hpoint : comap f x = fun i => aeval x (f (X i)) := by
    funext i
    exact comap_apply f x i
  rw [hpoint]
  exact pointToPoint_comap f x

end MvPolynomial
