/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/
module

public import Mathlib.RingTheory.MvPolynomial.Ideal

/-!
# The variable ideal in infinitely many variables

This module proves that the ideal generated by all variables in a multivariate
polynomial semiring is not finitely generated when the variable type is
infinite and the coefficient semiring is nontrivial.

Suppose finitely many polynomials generate the ideal. Their variables form a
finite set; evaluate those variables at zero and a fresh variable at one. Each
generator has zero constant coefficient, so evaluation annihilates the proposed
span, but evaluates the fresh variable to one, contradicting nontriviality.
This argument requires neither additive inverses nor countably many variables.

## References

* Ravi Vakil, *The Rising Sea: Foundations of Algebraic Geometry*, Exercise 6.7.E:
  motivation for the infinite-variable ideal statement (not the entire exercise).
* Mathlib, `Mathlib.RingTheory.MvPolynomial.Ideal`: `idealOfVars` and its
  finite-variable counterpart; `constantCoeff` is used in the proof.
-/

namespace MvPolynomial

/-- The ideal generated by all variables is not finitely generated when the
variable type is infinite and the coefficient semiring is nontrivial.
Motivated by Vakil, *The Rising Sea*, Exercise 6.7.E; this proves only the
non-finite-generation statement, not the exercise's short exact sequence. -/
public theorem idealOfVars_not_fg
    (k : Type*) (σ : Type*) [CommSemiring k] [Nontrivial k] [Infinite σ] :
    ¬ (idealOfVars σ k).FG := by
  classical
  rintro ⟨generators, hgenerators⟩
  let usedVars : Finset σ := generators.biUnion vars
  obtain ⟨fresh, hfresh⟩ := usedVars.exists_notMem
  let evaluate : MvPolynomial σ k →+* k :=
    eval₂Hom (RingHom.id k) fun i => if i ∈ usedVars then 0 else 1
  have idealOfVars_le_constantCoeff_ker :
      idealOfVars σ k ≤ RingHom.ker (constantCoeff : MvPolynomial σ k →+* k) := by
    rw [idealOfVars, Ideal.span_le]
    rintro _ ⟨i, rfl⟩
    simp
  have generators_le_ker :
      Ideal.span (generators : Set (MvPolynomial σ k)) ≤ RingHom.ker evaluate := by
    refine Ideal.span_le.2 ?_
    intro p hp
    change evaluate p = 0
    rw [eval₂Hom_eq_constantCoeff_of_vars]
    · rw [show constantCoeff p = 0 by
        have hpIdeal : p ∈ idealOfVars σ k := by
          rw [← hgenerators]
          exact Ideal.subset_span hp
        exact idealOfVars_le_constantCoeff_ker hpIdeal]
      rfl
    · intro i hi
      have himem : i ∈ usedVars := Finset.mem_biUnion.2 ⟨p, hp, hi⟩
      simp only [himem, ite_true]
  have fresh_mem_span :
      X fresh ∈ Ideal.span (generators : Set (MvPolynomial σ k)) := by
    rw [hgenerators]
    exact Ideal.subset_span ⟨fresh, rfl⟩
  have fresh_mem_ker := generators_le_ker fresh_mem_span
  change evaluate (X fresh) = 0 at fresh_mem_ker
  have : (1 : k) = 0 := by
    simpa only [evaluate, eval₂Hom_X', hfresh, ite_false] using fresh_mem_ker
  exact one_ne_zero this

end MvPolynomial
