/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/
module

public import MultivariatePolynomials.WeightOneValuation

/-!
# Naturality of subset-weight-one valuations

Injective changes of polynomial variables and field coefficients preserve the
minimum subset weight when source weights are the inverse image of target weights.
They induce maps of fraction fields, valuation rings and their entire residue
fields. Aligned pivots identify the residue map in the rational function fields
of unweighted variables and weighted ratios. If every image variable is
unweighted, the source function field instead maps into the target residue
field without choosing a source pivot.

The target can have additional variables of either weight. No finiteness
assumption is imposed on the index sets. A target residue field need not be
generated by the image of the source residue field.

## References

* Mathlib contributors, the multivariate polynomial `map` and `rename`,
  `IsFractionRing.map`, valuation subrings and local-ring residue maps.
* The subset-weight-one valuation and full-residue construction in
  `MultivariatePolynomials.WeightOneValuation`.
* Stefan Schröer, *A simple proof for Hochster's Theorem*, §2, for the
  specialization-valuation motivation and its indirect attribution to
  Y. Ershov. The pivot-ratio and full-residue formulation uses the
  independently repaired construction of the preceding module.
-/

@[expose] public section

open scoped WithZero

universe u v w z

namespace MvPolynomial

variable {σ : Type u} {τ : Type v}

/-- Map coefficients and then injectively rename the variables. -/
noncomputable def weightOnePolynomialMap {R : Type w} {A : Type z}
    [CommSemiring R] [CommSemiring A]
    (g : R →+* A) (e : σ ↪ τ) : MvPolynomial σ R →+* MvPolynomial τ A :=
  (rename (R := A) (e : σ → τ)).toRingHom.comp (map g)

@[simp] theorem weightOnePolynomialMap_C {R : Type w} {A : Type z}
    [CommSemiring R] [CommSemiring A] (g : R →+* A) (e : σ ↪ τ) (a : R) :
    weightOnePolynomialMap g e (C a) = C (g a) := by
  simp [weightOnePolynomialMap]

@[simp] theorem weightOnePolynomialMap_X {R : Type w} {A : Type z}
    [CommSemiring R] [CommSemiring A] (g : R →+* A) (e : σ ↪ τ) (j : σ) :
    weightOnePolynomialMap g e (X j) = X (e j) := by
  simp [weightOnePolynomialMap]

/-- Identity coefficient and variable maps induce the identity polynomial map. -/
theorem weightOnePolynomialMap_id {R : Type w} [CommSemiring R] :
    weightOnePolynomialMap (RingHom.id R)
      (⟨id, Function.injective_id⟩ : σ ↪ σ) =
        RingHom.id (MvPolynomial σ R) := by
  apply MvPolynomial.ringHom_ext
  · intro a
    simp
  · intro j
    simp

/-- Polynomial maps compose across independent coefficient and variable types. -/
theorem weightOnePolynomialMap_comp {υ : Type*} {R : Type w} {A : Type z} {B : Type*}
    [CommSemiring R] [CommSemiring A] [CommSemiring B]
    (g : R →+* A) (g' : A →+* B) (e : σ ↪ τ) (e' : τ ↪ υ) :
    weightOnePolynomialMap (g'.comp g) (e.trans e') =
      (weightOnePolynomialMap g' e').comp (weightOnePolynomialMap g e) := by
  apply MvPolynomial.ringHom_ext
  · intro a
    simp
  · intro j
    simp

theorem weightOnePolynomialMap_injective {R : Type w} {A : Type z}
    [CommSemiring R] [CommSemiring A] (g : R →+* A) (hg : Function.Injective g)
    (e : σ ↪ τ) : Function.Injective (weightOnePolynomialMap g e) :=
  (rename_injective (R := A) (e : σ → τ) e.injective).comp (map_injective g hg)

/-- Injective coefficient maps and embeddings preserve minimum support weight,
with the source weights pulled back from the target. -/
theorem weightOneOrder_map {R : Type w} {A : Type z} [CommSemiring R] [CommSemiring A]
    (g : R →+* A) (hg : Function.Injective g) (e : σ ↪ τ) (T : Set τ)
    (p : MvPolynomial σ R) :
    weightOneOrder T (weightOnePolynomialMap g e p) =
      weightOneOrder (e ⁻¹' T) p := by
  classical
  change weightOneOrder T (rename (R := A) (e : σ → τ) (map g p)) = _
  simp only [weightOneOrder, support_rename_of_injective e.injective,
    support_map_of_injective _ hg, Finset.inf_image]
  congr 1
  funext exponent
  change ((Finsupp.weight (fun j : τ => if j ∈ T then (1 : ℕ) else 0)
    (Finsupp.mapDomain e exponent) : ℕ) : ℕ∞) = _
  congr 1
  simp only [Finsupp.weight_apply]
  rw [Finsupp.sum_mapDomain_index (by simp) (by
    intro index coeff₁ coeff₂
    by_cases hin : index ∈ T <;> simp [hin])]
  rfl

/-- The finite minimum orders agree under renaming, including at zero. -/
theorem weightOneNatOrder_map {R : Type w} {A : Type z}
    [CommSemiring R] [CommSemiring A] (g : R →+* A) (hg : Function.Injective g)
    (e : σ ↪ τ) (T : Set τ) (p : MvPolynomial σ R) :
    weightOneNatOrder T (weightOnePolynomialMap g e p) =
      weightOneNatOrder (e ⁻¹' T) p := by
  exact congrArg ENat.toNat (weightOneOrder_map g hg e T p)

/-- At zero, both orders are infinite, independently of the embedding. -/
@[simp] theorem weightOneOrder_map_zero {R : Type w} {A : Type z}
    [CommSemiring R] [CommSemiring A] (g : R →+* A) (e : σ ↪ τ)
    (T : Set τ) :
    weightOneOrder T (weightOnePolynomialMap g e (0 : MvPolynomial σ R)) = ⊤ := by
  simp

/-- When every image variable is unweighted, a nonzero polynomial image has
minimum target order zero, over any pair of commutative semirings. -/
theorem weightOneOrder_map_eq_zero {R : Type w} {A : Type z}
    [CommSemiring R] [CommSemiring A] (g : R →+* A)
    (hg : Function.Injective g) (e : σ ↪ τ)
    (T : Set τ) (h : ∀ j : σ, e j ∉ T)
    {p : MvPolynomial σ R} (hp : p ≠ 0) :
    weightOneOrder T (weightOnePolynomialMap g e p) = 0 := by
  rw [weightOneOrder_map g hg e T p]
  have heq : e ⁻¹' T = (∅ : Set σ) := by
    ext j
    simp [h j]
  rw [heq]
  exact weightOneOrder_empty_of_ne_zero hp

variable {k : Type w} {l : Type z} [Field k] [Field l]

/-- The map on rational function fields induced by coefficient and variable embeddings. -/
noncomputable def weightOneFractionMap (g : k →+* l) (e : σ ↪ τ) :
    FractionRing (MvPolynomial σ k) →+* FractionRing (MvPolynomial τ l) :=
  IsFractionRing.map (j := weightOnePolynomialMap g e)
    (weightOnePolynomialMap_injective g g.injective e)

/-- The fraction map agrees with the polynomial map. -/
@[simp] theorem weightOneFractionMap_polynomial (g : k →+* l) (e : σ ↪ τ)
    (p : MvPolynomial σ k) :
    weightOneFractionMap g e (algebraMap (MvPolynomial σ k)
      (FractionRing (MvPolynomial σ k)) p) =
      algebraMap (MvPolynomial τ l) (FractionRing (MvPolynomial τ l))
        (weightOnePolynomialMap g e p) := by
  exact IsLocalization.map_eq (M := nonZeroDivisors (MvPolynomial σ k))
    (T := nonZeroDivisors (MvPolynomial τ l))
    (Q := FractionRing (MvPolynomial τ l))
    (nonZeroDivisors_le_comap_nonZeroDivisors_of_injective
      (weightOnePolynomialMap g e)
      (weightOnePolynomialMap_injective g g.injective e)) p

/-- The valuation subring of a subset-weight-one valuation. -/
noncomputable abbrev WeightOneValuationRing (S : Set σ) (i : S) :=
  (weightOneValuation (k := k) S i).valuationSubring

/-- A fraction-field embedding preserves the normalized valuation when the
weighted variables are precisely the preimage of the target weighted variables.
The two pivots are independent. -/
theorem weightOneValuation_map (g : k →+* l) (e : σ ↪ τ)
    (S : Set σ) (T : Set τ) (h : ∀ j : σ, e j ∈ T ↔ j ∈ S)
    (i : S) (t : T) (x : FractionRing (MvPolynomial σ k)) :
    weightOneValuation (k := l) T t (weightOneFractionMap g e x) =
      weightOneValuation (k := k) S i x := by
  obtain ⟨p, q, hq, rfl⟩ := IsFractionRing.div_surjective (MvPolynomial σ k) x
  have hq' : q ≠ 0 := mem_nonZeroDivisors_iff_ne_zero.mp hq
  have hweights : e ⁻¹' T = S := Set.ext fun j => h j
  by_cases hp : p = 0
  · subst p
    simp
  · have hpmap : weightOnePolynomialMap g e p ≠ 0 := by
      simpa only [map_zero] using (weightOnePolynomialMap_injective g g.injective e).ne hp
    have hqmap : weightOnePolynomialMap g e q ≠ 0 := by
      simpa only [map_zero] using (weightOnePolynomialMap_injective g g.injective e).ne hq'
    have hnat (r : MvPolynomial σ k) :
        weightOneNatOrder T (weightOnePolynomialMap g e r) = weightOneNatOrder S r := by
      rw [weightOneNatOrder_map g g.injective e T r, hweights]
    rw [map_div₀, weightOneFractionMap_polynomial, weightOneFractionMap_polynomial,
      weightOneValuation_div T t hpmap hqmap,
      weightOneValuation_div S i hp hq', hnat p, hnat q]

/-- Restriction of the fraction map to the valuation subrings. -/
noncomputable def weightOneValuationRingMap (g : k →+* l) (e : σ ↪ τ)
    (S : Set σ) (T : Set τ) (h : ∀ j : σ, e j ∈ T ↔ j ∈ S)
    (i : S) (t : T) :
    WeightOneValuationRing (k := k) S i →+* WeightOneValuationRing (k := l) T t :=
  ((weightOneFractionMap g e).comp
    (ValuationSubring.subtype (WeightOneValuationRing (k := k) S i))).codRestrict _
      (fun a => by
    rw [Valuation.mem_valuationSubring_iff]
    change weightOneValuation (k := l) T t
      (weightOneFractionMap g e (a : FractionRing (MvPolynomial σ k))) ≤ 1
    rw [weightOneValuation_map g e S T h i t]
    exact (Valuation.mem_valuationSubring_iff
      (weightOneValuation (k := k) S i)
      (a : FractionRing (MvPolynomial σ k))).mp a.property)

/-- Coercion of the restricted map recovers the ambient fraction map. -/
@[simp] theorem weightOneValuationRingMap_val (g : k →+* l) (e : σ ↪ τ)
    (S : Set σ) (T : Set τ) (h : ∀ j : σ, e j ∈ T ↔ j ∈ S)
    (i : S) (t : T) (a : WeightOneValuationRing (k := k) S i) :
    ((weightOneValuationRingMap g e S T h i t a :
      WeightOneValuationRing (k := l) T t) : FractionRing (MvPolynomial τ l)) =
        weightOneFractionMap g e (a : FractionRing (MvPolynomial σ k)) := rfl

/-- Preservation of the valuation makes the ring map local. -/
noncomputable instance weightOneValuationRingMap_isLocalHom (g : k →+* l)
    (e : σ ↪ τ) (S : Set σ) (T : Set τ)
    (h : ∀ j : σ, e j ∈ T ↔ j ∈ S) (i : S) (t : T) :
    IsLocalHom (weightOneValuationRingMap g e S T h i t) := by
  refine ⟨fun a ha => ?_⟩
  by_contra hunit
  have hmax : a ∈ IsLocalRing.maximalIdeal (WeightOneValuationRing (k := k) S i) :=
    (IsLocalRing.mem_maximalIdeal a).2 hunit
  have hlt := (Valuation.mem_maximalIdeal_iff
    (v := weightOneValuation (k := k) S i)).1 hmax
  have htarget : weightOneValuationRingMap g e S T h i t a ∈
      IsLocalRing.maximalIdeal (WeightOneValuationRing (k := l) T t) := by
    apply (Valuation.mem_maximalIdeal_iff
      (v := weightOneValuation (k := l) T t)).2
    simpa [weightOneValuationRingMap_val, weightOneValuation_map g e S T h i t] using hlt
  exact (IsLocalRing.mem_maximalIdeal _).1 htarget ha

/-- The induced map of the full residue fields. -/
noncomputable def weightOneResidueMap (g : k →+* l) (e : σ ↪ τ)
    (S : Set σ) (T : Set τ) (h : ∀ j : σ, e j ∈ T ↔ j ∈ S)
    (i : S) (t : T) :
    IsLocalRing.ResidueField (WeightOneValuationRing (k := k) S i) →+*
      IsLocalRing.ResidueField (WeightOneValuationRing (k := l) T t) :=
  IsLocalRing.ResidueField.map (weightOneValuationRingMap g e S T h i t)

/-- Reduction commutes with the induced map of valuation rings. -/
@[simp] theorem weightOneResidueMap_residue (g : k →+* l) (e : σ ↪ τ)
    (S : Set σ) (T : Set τ) (h : ∀ j : σ, e j ∈ T ↔ j ∈ S)
    (i : S) (t : T) (a : WeightOneValuationRing (k := k) S i) :
    weightOneResidueMap g e S T h i t
      (IsLocalRing.residue _ a) =
      IsLocalRing.residue _ (weightOneValuationRingMap g e S T h i t a) := by
  exact IsLocalRing.ResidueField.map_residue _ _

/-- The target pivot aligned with the image of the source pivot. -/
def weightOneAlignedPivot (e : σ ↪ τ) (S : Set σ) (T : Set τ)
    (h : ∀ j : σ, e j ∈ T ↔ j ∈ S) (i : S) : T :=
  ⟨e i, (h i).2 i.property⟩

/-- Unweighted variables map to unweighted variables, and weighted ratios
map to ratios relative to the aligned pivot. -/
def weightOneCoefficientVariablesEmbedding (e : σ ↪ τ) (S : Set σ) (T : Set τ)
    (h : ∀ j : σ, e j ∈ T ↔ j ∈ S) (i : S) :
    WeightOneCoefficientVariables S i ↪
      WeightOneCoefficientVariables T (weightOneAlignedPivot e S T h i) where
  toFun
    | .inl j => .inl ⟨e j, fun hj => j.property ((h j).1 hj)⟩
    | .inr j => .inr ⟨e j, (h j).2 j.property.1,
        fun hj => j.property.2 (e.injective hj)⟩
  inj' := by
    intro a b hab
    cases a with
    | inl a =>
      cases b with
      | inl b => congr 1; exact Subtype.ext (e.injective (congrArg Subtype.val (Sum.inl.inj hab)))
      | inr b => cases hab
    | inr a =>
      cases b with
      | inl b => cases hab
      | inr b => congr 1; exact Subtype.ext (e.injective (congrArg Subtype.val (Sum.inr.inj hab)))

/-- An unweighted coefficient index maps to its unweighted target index. -/
@[simp] theorem weightOneCoefficientVariablesEmbedding_inl (e : σ ↪ τ)
    (S : Set σ) (T : Set τ) (h : ∀ j : σ, e j ∈ T ↔ j ∈ S)
    (i : S) (j : {j : σ // j ∉ S}) :
    weightOneCoefficientVariablesEmbedding e S T h i (Sum.inl j) =
      Sum.inl (⟨e j, fun hj => j.property ((h j).1 hj)⟩ : {j : τ // j ∉ T}) := rfl

/-- A weighted ratio index maps to its aligned target ratio index. -/
@[simp] theorem weightOneCoefficientVariablesEmbedding_inr (e : σ ↪ τ)
    (S : Set σ) (T : Set τ) (h : ∀ j : σ, e j ∈ T ↔ j ∈ S)
    (i : S) (j : {j : σ // j ∈ S ∧ j ≠ (i : σ)}) :
    weightOneCoefficientVariablesEmbedding e S T h i (Sum.inr j) =
      Sum.inr (⟨e j, (h j).2 j.property.1,
        fun hj => j.property.2 (e.injective hj)⟩ :
        {j : τ // j ∈ T ∧ j ≠ (weightOneAlignedPivot e S T h i : τ)}) := rfl

/-- The coefficient-field embedding in aligned-pivot coordinates. -/
noncomputable def weightOneCoefficientFieldMap (g : k →+* l) (e : σ ↪ τ)
    (S : Set σ) (T : Set τ) (h : ∀ j : σ, e j ∈ T ↔ j ∈ S) (i : S) :
    WeightOneCoefficientField k S i →+*
      WeightOneCoefficientField l T (weightOneAlignedPivot e S T h i) :=
  weightOneFractionMap g (weightOneCoefficientVariablesEmbedding e S T h i)

private noncomputable def weightOneValuationRingEquiv (T : Set τ) (t t' : T) :
    WeightOneValuationRing (k := l) T t ≃+* WeightOneValuationRing (k := l) T t' := by
  apply RingEquiv.restrict (RingEquiv.refl (FractionRing (MvPolynomial τ l)))
  intro x
  change weightOneValuation (k := l) T t x ≤ 1 ↔
    weightOneValuation (k := l) T t' x ≤ 1
  rw [weightOneValuation_pivot_eq T t t']

private theorem weightOneValuationRingEquiv_val (T : Set τ) (t t' : T)
    (a : WeightOneValuationRing (k := l) T t) :
    ((weightOneValuationRingEquiv (l := l) T t t' a :
      WeightOneValuationRing (k := l) T t') : FractionRing (MvPolynomial τ l)) =
    (a : FractionRing (MvPolynomial τ l)) := rfl

private theorem weightOneValuationRingEquiv_self (T : Set τ) (t : T) :
    weightOneValuationRingEquiv (l := l) T t t = RingEquiv.refl _ := by
  apply RingEquiv.ext
  intro a
  apply Subtype.ext
  rfl

private theorem weightOneValuationRingEquiv_trans (T : Set τ) (t t' t'' : T) :
    (weightOneValuationRingEquiv (l := l) T t t').trans
      (weightOneValuationRingEquiv (l := l) T t' t'') =
      weightOneValuationRingEquiv (l := l) T t t'' := by
  apply RingEquiv.ext
  intro a
  apply Subtype.ext
  rfl

/-- The coordinate change between two choices of target pivot. -/
@[no_expose]
noncomputable def weightOneCoefficientChangePivot (T : Set τ) (t t' : T) :
    WeightOneCoefficientField l T t ≃+* WeightOneCoefficientField l T t' := by
  let cast : WeightOneValuationRing (k := l) T t ≃+*
      WeightOneValuationRing (k := l) T t' := by
    apply RingEquiv.restrict (RingEquiv.refl (FractionRing (MvPolynomial τ l)))
    intro x
    change weightOneValuation (k := l) T t x ≤ 1 ↔
      weightOneValuation (k := l) T t' x ≤ 1
    rw [weightOneValuation_pivot_eq T t t']
  exact (weightOneResidueEquiv T t).symm.trans
    ((IsLocalRing.ResidueField.mapEquiv cast).trans
      (weightOneResidueEquiv T t'))

private theorem weightOneCoefficientChangePivot_of_sections (T : Set τ) (t t' : T)
    (a : WeightOneCoefficientField l T t) (b : WeightOneCoefficientField l T t')
    (h : ((weightOneCoefficientSection T t a : WeightOneValuationRing (k := l) T t) :
        FractionRing (MvPolynomial τ l)) =
      ((weightOneCoefficientSection T t' b : WeightOneValuationRing (k := l) T t') :
        FractionRing (MvPolynomial τ l))) :
    weightOneCoefficientChangePivot (l := l) T t t' a = b := by
  simp only [weightOneCoefficientChangePivot, RingEquiv.trans_apply]
  change weightOneResidueEquiv T t'
      (IsLocalRing.ResidueField.mapEquiv (weightOneValuationRingEquiv T t t')
        ((weightOneResidueEquiv T t).symm a)) = b
  rw [weightOneResidueEquiv_symm_apply,
    IsLocalRing.ResidueField.mapEquiv_apply, IsLocalRing.ResidueField.map_residue]
  have heq_sections : weightOneValuationRingEquiv (l := l) T t t'
      (weightOneCoefficientSection T t a) = weightOneCoefficientSection T t' b :=
    Subtype.ext ((weightOneValuationRingEquiv_val T t t' _).trans h)
  change weightOneResidueEquiv T t'
    (IsLocalRing.residue _
      (weightOneValuationRingEquiv T t t' (weightOneCoefficientSection T t a))) = b
  rw [heq_sections, weightOneResidueEquiv_section]

local notation3 "ratio[" F "," U "," pivot "](" j ")" =>
  (algebraMap (MvPolynomial (WeightOneCoefficientVariables U pivot) F)
    (WeightOneCoefficientField F U pivot) (X (Sum.inr j)))

local notation3 "unweighted[" F "," U "," pivot "](" j ")" =>
  (algebraMap (MvPolynomial (WeightOneCoefficientVariables U pivot) F)
    (WeightOneCoefficientField F U pivot) (X (Sum.inl j)))

/-- Pivot changes preserve coefficient constants. -/
@[simp] theorem weightOneCoefficientChangePivot_C (T : Set τ) (t t' : T) (a : l) :
    weightOneCoefficientChangePivot (l := l) T t t'
      (algebraMap (MvPolynomial (WeightOneCoefficientVariables T t) l)
        (WeightOneCoefficientField l T t) (C a)) =
      algebraMap (MvPolynomial (WeightOneCoefficientVariables T t') l)
        (WeightOneCoefficientField l T t') (C a) := by
  apply weightOneCoefficientChangePivot_of_sections
  rw [weightOneCoefficientSection_C_val, weightOneCoefficientSection_C_val]

/-- Pivot changes preserve every unweighted generator. -/
@[simp] theorem weightOneCoefficientChangePivot_unweighted (T : Set τ) (t t' : T)
    (j : {j : τ // j ∉ T}) :
    weightOneCoefficientChangePivot (l := l) T t t' (unweighted[l, T, t](j)) =
      unweighted[l, T, t'](j) := by
  apply weightOneCoefficientChangePivot_of_sections
  rw [weightOneCoefficientSection_unweighted_val, weightOneCoefficientSection_unweighted_val]

/-- Switching from `t` to `t'` sends the ratio `t'/t` to `(t/t')⁻¹`. -/
theorem weightOneCoefficientChangePivot_ratio_pivot (T : Set τ) (t t' : T)
    (ht : (t : τ) ≠ t') :
    weightOneCoefficientChangePivot (l := l) T t t'
      (ratio[l, T, t](⟨t', t'.property, Ne.symm ht⟩)) =
        (ratio[l, T, t'](⟨t, t.property, ht⟩))⁻¹ := by
  apply weightOneCoefficientChangePivot_of_sections
  let sectionToField : WeightOneCoefficientField l T t' →+*
      FractionRing (MvPolynomial τ l) :=
    (ValuationSubring.subtype (WeightOneValuationRing (k := l) T t')).comp
      (weightOneCoefficientSection T t')
  change _ = sectionToField ((ratio[l, T, t'](⟨t, t.property, ht⟩))⁻¹)
  rw [map_inv₀]
  change _ = (((weightOneCoefficientSection T t'
    (ratio[l, T, t'](⟨t, t.property, ht⟩)) :
      WeightOneValuationRing (k := l) T t') : FractionRing (MvPolynomial τ l)))⁻¹
  rw [weightOneCoefficientSection_ratio_val, weightOneCoefficientSection_ratio_val]
  simp only [inv_div]

/-- Other weighted ratios change by division by the old pivot's new coordinate. -/
theorem weightOneCoefficientChangePivot_ratio_of_ne (T : Set τ) (t t' : T)
    (ht : (t : τ) ≠ t') (j : {j : τ // j ∈ T ∧ j ≠ (t : τ)})
    (hj : (j : τ) ≠ t') :
    weightOneCoefficientChangePivot (l := l) T t t' (ratio[l, T, t](j)) =
      ratio[l, T, t'](⟨j, j.property.1, hj⟩) /
        ratio[l, T, t'](⟨t, t.property, ht⟩) := by
  apply weightOneCoefficientChangePivot_of_sections
  let sectionToField : WeightOneCoefficientField l T t' →+*
      FractionRing (MvPolynomial τ l) :=
    (ValuationSubring.subtype (WeightOneValuationRing (k := l) T t')).comp
      (weightOneCoefficientSection T t')
  change _ = sectionToField
    (ratio[l, T, t'](⟨j, j.property.1, hj⟩) /
      ratio[l, T, t'](⟨t, t.property, ht⟩))
  rw [map_div₀]
  change _ =
    (((weightOneCoefficientSection T t' (ratio[l, T, t'](⟨j, j.property.1, hj⟩)) :
      WeightOneValuationRing (k := l) T t') : FractionRing (MvPolynomial τ l))) /
    (((weightOneCoefficientSection T t' (ratio[l, T, t'](⟨t, t.property, ht⟩)) :
      WeightOneValuationRing (k := l) T t') : FractionRing (MvPolynomial τ l)))
  rw [weightOneCoefficientSection_ratio_val, weightOneCoefficientSection_ratio_val,
    weightOneCoefficientSection_ratio_val]
  have ht' : algebraMap (MvPolynomial τ l) (FractionRing (MvPolynomial τ l))
      (X (t' : τ)) ≠ 0 := by
    intro hzero
    exact (X_ne_zero (t' : τ) (R := l)) (IsFractionRing.to_map_eq_zero_iff.mp hzero)
  field_simp

/-- The fraction map respects total field division. Rational-fraction
representations used for valuations require a nonzero denominator. -/
@[simp] theorem weightOneFractionMap_div (g : k →+* l) (e : σ ↪ τ)
    (p q : MvPolynomial σ k) :
    weightOneFractionMap g e
      (algebraMap (MvPolynomial σ k) (FractionRing (MvPolynomial σ k)) p /
        algebraMap (MvPolynomial σ k) (FractionRing (MvPolynomial σ k)) q) =
      algebraMap (MvPolynomial τ l) (FractionRing (MvPolynomial τ l))
        (weightOnePolynomialMap g e p) /
      algebraMap (MvPolynomial τ l) (FractionRing (MvPolynomial τ l))
        (weightOnePolynomialMap g e q) := by
  simp

/-- Identity renaming and the identity coefficient map induce the identity field map. -/
theorem weightOneFractionMap_id :
    weightOneFractionMap (RingHom.id k)
      (⟨id, Function.injective_id⟩ : σ ↪ σ) =
      RingHom.id (FractionRing (MvPolynomial σ k)) := by
  apply IsFractionRing.ringHom_ext (A := MvPolynomial σ k)
  intro p
  simpa only [weightOneFractionMap_polynomial, RingHom.id_apply] using
    congrArg (algebraMap (MvPolynomial σ k) (FractionRing (MvPolynomial σ k)))
      (DFunLike.congr_fun (weightOnePolynomialMap_id (R := k) (σ := σ)) p)

/-- Fraction maps compose across independent coefficient fields and index sets. -/
theorem weightOneFractionMap_comp {υ : Type*} {m : Type*} [Field m]
    (g : k →+* l) (g' : l →+* m) (e : σ ↪ τ) (e' : τ ↪ υ) :
    weightOneFractionMap (g'.comp g) (e.trans e') =
      (weightOneFractionMap g' e').comp (weightOneFractionMap g e) := by
  apply IsFractionRing.ringHom_ext (A := MvPolynomial σ k)
  intro p
  simp [weightOnePolynomialMap_comp]

/-- With identity variables and coefficients, the valuation-ring map is the identity. -/
theorem weightOneValuationRingMap_id (S : Set σ) (i : S) :
    weightOneValuationRingMap (RingHom.id k)
      (⟨id, Function.injective_id⟩ : σ ↪ σ) S S (fun _ => Iff.rfl) i i =
      RingHom.id (WeightOneValuationRing (k := k) S i) := by
  ext a
  simpa only [weightOneValuationRingMap_val, RingHom.id_apply] using
    DFunLike.congr_fun (weightOneFractionMap_id (k := k) (σ := σ))
      (a : FractionRing (MvPolynomial σ k))

/-- Valuation-ring maps compose across arbitrary independent pivots. -/
theorem weightOneValuationRingMap_comp {υ : Type*} {m : Type*} [Field m]
    (g : k →+* l) (g' : l →+* m) (e : σ ↪ τ) (e' : τ ↪ υ)
    (S : Set σ) (T : Set τ) (U : Set υ)
    (h : ∀ j : σ, e j ∈ T ↔ j ∈ S)
    (h' : ∀ j : τ, e' j ∈ U ↔ j ∈ T)
    (i : S) (t : T) (r : U) :
    weightOneValuationRingMap (g'.comp g) (e.trans e') S U
      (fun j => (h' (e j)).trans (h j)) i r =
      (weightOneValuationRingMap g' e' T U h' t r).comp
        (weightOneValuationRingMap g e S T h i t) := by
  ext a
  change weightOneFractionMap (g'.comp g) (e.trans e')
      (a : FractionRing (MvPolynomial σ k)) =
    weightOneFractionMap g' e' (weightOneFractionMap g e
      (a : FractionRing (MvPolynomial σ k)))
  exact DFunLike.congr_fun (weightOneFractionMap_comp g g' e e')
    (a : FractionRing (MvPolynomial σ k))

/-- Identity renaming induces the identity on the full residue field. -/
theorem weightOneResidueMap_id (S : Set σ) (i : S) :
    weightOneResidueMap (RingHom.id k)
      (⟨id, Function.injective_id⟩ : σ ↪ σ) S S (fun _ => Iff.rfl) i i =
      RingHom.id (IsLocalRing.ResidueField (WeightOneValuationRing (k := k) S i)) := by
  apply Ideal.Quotient.ringHom_ext
  apply RingHom.ext
  intro a
  change weightOneResidueMap (RingHom.id k)
      (⟨id, Function.injective_id⟩ : σ ↪ σ) S S (fun _ => Iff.rfl) i i
      (IsLocalRing.residue _ a) = IsLocalRing.residue _ a
  rw [weightOneResidueMap_residue,
    DFunLike.congr_fun (weightOneValuationRingMap_id S i) a, RingHom.id_apply]

/-- Maps of full residue fields compose for independent pivots. -/
theorem weightOneResidueMap_comp {υ : Type*} {m : Type*} [Field m]
    (g : k →+* l) (g' : l →+* m) (e : σ ↪ τ) (e' : τ ↪ υ)
    (S : Set σ) (T : Set τ) (U : Set υ)
    (h : ∀ j : σ, e j ∈ T ↔ j ∈ S)
    (h' : ∀ j : τ, e' j ∈ U ↔ j ∈ T)
    (i : S) (t : T) (r : U) :
    weightOneResidueMap (g'.comp g) (e.trans e') S U
      (fun j => (h' (e j)).trans (h j)) i r =
      (weightOneResidueMap g' e' T U h' t r).comp
        (weightOneResidueMap g e S T h i t) := by
  apply Ideal.Quotient.ringHom_ext
  apply RingHom.ext
  intro a
  change weightOneResidueMap (g'.comp g) (e.trans e') S U
      (fun j => (h' (e j)).trans (h j)) i r (IsLocalRing.residue _ a) =
    weightOneResidueMap g' e' T U h' t r
      (weightOneResidueMap g e S T h i t (IsLocalRing.residue _ a))
  rw [weightOneResidueMap_residue]
  exact congrArg (IsLocalRing.residue _)
    (DFunLike.congr_fun (weightOneValuationRingMap_comp g g' e e' S T U h h' i t r) a)

/-- Coefficient constants map by the coefficient field homomorphism. -/
@[simp] theorem weightOneCoefficientFieldMap_C (g : k →+* l) (e : σ ↪ τ)
    (S : Set σ) (T : Set τ) (h : ∀ j : σ, e j ∈ T ↔ j ∈ S)
    (i : S) (a : k) :
    weightOneCoefficientFieldMap g e S T h i
      (algebraMap (MvPolynomial (WeightOneCoefficientVariables S i) k)
        (WeightOneCoefficientField k S i) (C a)) =
    algebraMap (MvPolynomial
        (WeightOneCoefficientVariables T (weightOneAlignedPivot e S T h i)) l)
      (WeightOneCoefficientField l T (weightOneAlignedPivot e S T h i)) (C (g a)) := by
  simp [weightOneCoefficientFieldMap]

/-- An unweighted variable maps to its unweighted target coefficient. -/
@[simp] theorem weightOneCoefficientFieldMap_unweighted (g : k →+* l) (e : σ ↪ τ)
    (S : Set σ) (T : Set τ) (h : ∀ j : σ, e j ∈ T ↔ j ∈ S)
    (i : S) (j : {j : σ // j ∉ S}) :
    weightOneCoefficientFieldMap g e S T h i
      (algebraMap (MvPolynomial (WeightOneCoefficientVariables S i) k)
        (WeightOneCoefficientField k S i) (X (Sum.inl j))) =
      algebraMap (MvPolynomial
          (WeightOneCoefficientVariables T (weightOneAlignedPivot e S T h i)) l)
        (WeightOneCoefficientField l T (weightOneAlignedPivot e S T h i))
          (X (weightOneCoefficientVariablesEmbedding e S T h i (Sum.inl j))) := by
  simp [weightOneCoefficientFieldMap]

/-- A weighted ratio maps to its corresponding target ratio coordinate. -/
@[simp] theorem weightOneCoefficientFieldMap_ratio (g : k →+* l) (e : σ ↪ τ)
    (S : Set σ) (T : Set τ) (h : ∀ j : σ, e j ∈ T ↔ j ∈ S)
    (i : S) (j : {j : σ // j ∈ S ∧ j ≠ (i : σ)}) :
    weightOneCoefficientFieldMap g e S T h i
      (algebraMap (MvPolynomial (WeightOneCoefficientVariables S i) k)
        (WeightOneCoefficientField k S i) (X (Sum.inr j))) =
      algebraMap (MvPolynomial
          (WeightOneCoefficientVariables T (weightOneAlignedPivot e S T h i)) l)
        (WeightOneCoefficientField l T (weightOneAlignedPivot e S T h i))
          (X (weightOneCoefficientVariablesEmbedding e S T h i (Sum.inr j))) := by
  simp [weightOneCoefficientFieldMap]

/-- The coefficient sections commute with the valuation-ring map in aligned
pivot coordinates, on the entire coefficient field. -/
theorem weightOneCoefficientSection_map (g : k →+* l) (e : σ ↪ τ)
    (S : Set σ) (T : Set τ) (h : ∀ j : σ, e j ∈ T ↔ j ∈ S)
    (i : S) (a : WeightOneCoefficientField k S i) :
    weightOneValuationRingMap g e S T h i (weightOneAlignedPivot e S T h i)
      (weightOneCoefficientSection S i a) =
    weightOneCoefficientSection T (weightOneAlignedPivot e S T h i)
      (weightOneCoefficientFieldMap g e S T h i a) := by
  let sourceRing := WeightOneValuationRing (k := k) S i
  let targetRing := WeightOneValuationRing (k := l) T (weightOneAlignedPivot e S T h i)
  let sourcePolynomial := MvPolynomial (WeightOneCoefficientVariables S i) k
  let sourceField := WeightOneCoefficientField k S i
  let sourceFraction := FractionRing (MvPolynomial σ k)
  let targetField := FractionRing (MvPolynomial τ l)
  let left : sourceField →+* targetField :=
    (weightOneFractionMap g e).comp
      ((ValuationSubring.subtype sourceRing).comp (weightOneCoefficientSection S i))
  let right : sourceField →+* targetField :=
    (ValuationSubring.subtype targetRing).comp
      ((weightOneCoefficientSection T (weightOneAlignedPivot e S T h i)).comp
        (weightOneCoefficientFieldMap g e S T h i))
  have hfield : left = right := by
    apply IsFractionRing.ringHom_ext
      (A := MvPolynomial (WeightOneCoefficientVariables S i) k)
    intro p
    have hpoly : left.comp (algebraMap sourcePolynomial sourceField) =
        right.comp (algebraMap sourcePolynomial sourceField) := by
      apply MvPolynomial.ringHom_ext
      · intro c
        change weightOneFractionMap g e
          ((weightOneCoefficientSection S i
            (algebraMap sourcePolynomial sourceField (C c)) : sourceRing) :
              sourceFraction) =
          ((weightOneCoefficientSection T (weightOneAlignedPivot e S T h i)
            (weightOneCoefficientFieldMap g e S T h i
              (algebraMap sourcePolynomial sourceField (C c))) : targetRing) :
              targetField)
        rw [weightOneCoefficientSection_C_val, weightOneFractionMap_polynomial,
          weightOnePolynomialMap_C, weightOneCoefficientFieldMap_C,
          weightOneCoefficientSection_C_val]
      · intro j
        cases j with
        | inl j =>
          change weightOneFractionMap g e
            ((weightOneCoefficientSection S i
              (algebraMap sourcePolynomial sourceField (X (Sum.inl j))) : sourceRing) :
                sourceFraction) =
            ((weightOneCoefficientSection T (weightOneAlignedPivot e S T h i)
              (weightOneCoefficientFieldMap g e S T h i
                (algebraMap sourcePolynomial sourceField (X (Sum.inl j)))) : targetRing) :
                targetField)
          rw [weightOneCoefficientSection_unweighted_val, weightOneFractionMap_polynomial,
            weightOnePolynomialMap_X, weightOneCoefficientFieldMap_unweighted,
            weightOneCoefficientVariablesEmbedding_inl,
            weightOneCoefficientSection_unweighted_val]
        | inr j =>
          change weightOneFractionMap g e
            ((weightOneCoefficientSection S i
              (algebraMap sourcePolynomial sourceField (X (Sum.inr j))) : sourceRing) :
                sourceFraction) =
            ((weightOneCoefficientSection T (weightOneAlignedPivot e S T h i)
              (weightOneCoefficientFieldMap g e S T h i
                (algebraMap sourcePolynomial sourceField (X (Sum.inr j)))) : targetRing) :
                targetField)
          rw [weightOneCoefficientSection_ratio_val, weightOneFractionMap_div,
            weightOnePolynomialMap_X, weightOnePolynomialMap_X,
            weightOneCoefficientFieldMap_ratio,
            weightOneCoefficientVariablesEmbedding_inr,
            weightOneCoefficientSection_ratio_val]
          rfl
    exact DFunLike.congr_fun hpoly p
  apply Subtype.ext
  exact DFunLike.congr_fun hfield a

/-- The full-residue square commutes in aligned-pivot coordinates. -/
theorem weightOneResidueEquiv_map (g : k →+* l) (e : σ ↪ τ)
    (S : Set σ) (T : Set τ) (h : ∀ j : σ, e j ∈ T ↔ j ∈ S)
    (i : S) (r : IsLocalRing.ResidueField (WeightOneValuationRing (k := k) S i)) :
    weightOneResidueEquiv T (weightOneAlignedPivot e S T h i)
      (weightOneResidueMap g e S T h i (weightOneAlignedPivot e S T h i) r) =
        weightOneCoefficientFieldMap g e S T h i (weightOneResidueEquiv S i r) := by
  have hr : r = IsLocalRing.residue _
      (weightOneCoefficientSection S i (weightOneResidueEquiv S i r)) := by
    rw [← weightOneResidueEquiv_symm_apply, RingEquiv.symm_apply_apply]
  rw [hr, weightOneResidueMap_residue, weightOneCoefficientSection_map,
    weightOneResidueEquiv_section, weightOneResidueEquiv_section]

/-- The arbitrary-pivot square explicitly changes coefficient coordinates. -/
theorem weightOneResidueEquiv_map_changePivot (g : k →+* l) (e : σ ↪ τ)
    (S : Set σ) (T : Set τ) (h : ∀ j : σ, e j ∈ T ↔ j ∈ S)
    (i : S) (t : T)
    (r : IsLocalRing.ResidueField (WeightOneValuationRing (k := k) S i)) :
    weightOneResidueEquiv T t (weightOneResidueMap g e S T h i t r) =
      weightOneCoefficientChangePivot (l := l) T
        (weightOneAlignedPivot e S T h i) t
        (weightOneCoefficientFieldMap g e S T h i (weightOneResidueEquiv S i r)) := by
  let aligned := weightOneAlignedPivot e S T h i
  let cast := weightOneValuationRingEquiv (l := l) T aligned t
  have hres : weightOneResidueMap g e S T h i t r =
      IsLocalRing.ResidueField.mapEquiv cast
        (weightOneResidueMap g e S T h i aligned r) := by
    obtain ⟨a, rfl⟩ := IsLocalRing.residue_surjective r
    have hcompat : weightOneValuationRingMap g e S T h i t a =
        cast (weightOneValuationRingMap g e S T h i aligned a) := by
      apply Subtype.ext
      change weightOneFractionMap g e (a : FractionRing (MvPolynomial σ k)) =
        (((cast (weightOneValuationRingMap g e S T h i aligned a) :
          WeightOneValuationRing (k := l) T t)) : FractionRing (MvPolynomial τ l))
      rw [weightOneValuationRingEquiv_val]
      rfl
    simpa only [weightOneResidueMap_residue,
      IsLocalRing.ResidueField.mapEquiv_apply, IsLocalRing.ResidueField.map_residue,
      RingEquiv.coe_toRingHom] using
      congrArg (IsLocalRing.residue (WeightOneValuationRing (k := l) T t)) hcompat
  rw [hres, ← weightOneResidueEquiv_map g e S T h i r]
  simp only [weightOneCoefficientChangePivot, RingEquiv.trans_apply]
  change weightOneResidueEquiv T t
      (IsLocalRing.ResidueField.mapEquiv cast
        (weightOneResidueMap g e S T h i aligned r)) =
    weightOneResidueEquiv T t
      (IsLocalRing.ResidueField.mapEquiv cast
        ((weightOneResidueEquiv T aligned).symm
          (weightOneResidueEquiv T aligned
            (weightOneResidueMap g e S T h i aligned r))))
  rw [RingEquiv.symm_apply_apply]

/-- Changing to the same pivot leaves the coefficient coordinates unchanged. -/
theorem weightOneCoefficientChangePivot_self (T : Set τ) (t : T) :
    weightOneCoefficientChangePivot (l := l) T t t = RingEquiv.refl _ := by
  apply RingEquiv.ext
  intro a
  exact weightOneCoefficientChangePivot_of_sections T t t a a rfl

/-- With the same pivot, each weighted ratio retains its coordinate. -/
@[simp] theorem weightOneCoefficientChangePivot_ratio_self (T : Set τ) (t : T)
    (j : {j : τ // j ∈ T ∧ j ≠ (t : τ)}) :
    weightOneCoefficientChangePivot (l := l) T t t (ratio[l, T, t](j)) =
      ratio[l, T, t](j) := by
  rw [weightOneCoefficientChangePivot_self]
  rfl

/-- Coordinate changes between pivots compose. -/
theorem weightOneCoefficientChangePivot_trans (T : Set τ) (t t' t'' : T) :
    (weightOneCoefficientChangePivot (l := l) T t t').trans
      (weightOneCoefficientChangePivot (l := l) T t' t'') =
    weightOneCoefficientChangePivot (l := l) T t t'' := by
  let first := weightOneValuationRingEquiv (l := l) T t t'
  let second := weightOneValuationRingEquiv (l := l) T t' t''
  let direct := weightOneValuationRingEquiv (l := l) T t t''
  have hcomp : first.trans second = direct :=
    weightOneValuationRingEquiv_trans T t t' t''
  apply RingEquiv.ext
  intro a
  simp only [weightOneCoefficientChangePivot, RingEquiv.trans_apply]
  change weightOneResidueEquiv T t''
      (IsLocalRing.ResidueField.mapEquiv second
        ((weightOneResidueEquiv T t').symm
          (weightOneResidueEquiv T t'
            (IsLocalRing.ResidueField.mapEquiv first
              ((weightOneResidueEquiv T t).symm a))))) =
    weightOneResidueEquiv T t''
      (IsLocalRing.ResidueField.mapEquiv direct
        ((weightOneResidueEquiv T t).symm a))
  simp only [RingEquiv.symm_apply_apply]
  change weightOneResidueEquiv T t''
      (((IsLocalRing.ResidueField.mapEquiv first).trans
        (IsLocalRing.ResidueField.mapEquiv second))
          ((weightOneResidueEquiv T t).symm a)) =
    weightOneResidueEquiv T t''
      (IsLocalRing.ResidueField.mapEquiv direct
        ((weightOneResidueEquiv T t).symm a))
  rw [← IsLocalRing.ResidueField.mapEquiv_trans, hcomp]

/-- A nonzero source function with unweighted image variables has target
valuation one. Only a target pivot is required. -/
theorem weightOneValuation_map_of_disjoint (g : k →+* l) (e : σ ↪ τ)
    (T : Set τ) (h : ∀ j : σ, e j ∉ T) (t : T)
    {x : FractionRing (MvPolynomial σ k)} (hx : x ≠ 0) :
    weightOneValuation (k := l) T t (weightOneFractionMap g e x) = 1 := by
  obtain ⟨p, q, hq, rfl⟩ := IsFractionRing.div_surjective (MvPolynomial σ k) x
  have hq' : q ≠ 0 := mem_nonZeroDivisors_iff_ne_zero.mp hq
  have hp : p ≠ 0 := by
    intro hzero
    subst p
    simp at hx
  have hpmap : weightOnePolynomialMap g e p ≠ 0 := by
    simpa only [map_zero] using (weightOnePolynomialMap_injective g g.injective e).ne hp
  have hqmap : weightOnePolynomialMap g e q ≠ 0 := by
    simpa only [map_zero] using (weightOnePolynomialMap_injective g g.injective e).ne hq'
  have horder (r : MvPolynomial σ k) (hr : r ≠ 0) :
      weightOneNatOrder T (weightOnePolynomialMap g e r) = 0 := by
    have heq := weightOneOrder_map_eq_zero g g.injective e T h hr
    exact congrArg ENat.toNat heq
  rw [weightOneFractionMap_div, weightOneValuation_div T t hpmap hqmap,
    horder p hp, horder q hq']
  simp

/-- All source rational functions map into the target valuation ring when
their variables are unweighted there, even if the source has no pivot. -/
noncomputable def weightOneZeroValuationRingMap (g : k →+* l) (e : σ ↪ τ)
    (T : Set τ) (h : ∀ j : σ, e j ∉ T) (t : T) :
    FractionRing (MvPolynomial σ k) →+* WeightOneValuationRing (k := l) T t :=
  (weightOneFractionMap g e).codRestrict _ (fun x => by
    rw [Valuation.mem_valuationSubring_iff]
    by_cases hx : x = 0
    · simp [hx]
    · rw [weightOneValuation_map_of_disjoint g e T h t hx])

/-- Reduction of the all-unweighted-image map into the full residue field. -/
noncomputable def weightOneZeroResidueMap (g : k →+* l) (e : σ ↪ τ)
    (T : Set τ) (h : ∀ j : σ, e j ∉ T) (t : T) :
    FractionRing (MvPolynomial σ k) →+*
      IsLocalRing.ResidueField (WeightOneValuationRing (k := l) T t) :=
  (IsLocalRing.residue _).comp (weightOneZeroValuationRingMap g e T h t)

/-- The zero-image-weight ring map agrees with the ambient fraction map. -/
@[simp] theorem weightOneZeroValuationRingMap_val (g : k →+* l) (e : σ ↪ τ)
    (T : Set τ) (h : ∀ j : σ, e j ∉ T) (t : T)
    (x : FractionRing (MvPolynomial σ k)) :
    ((weightOneZeroValuationRingMap g e T h t x :
      WeightOneValuationRing (k := l) T t) : FractionRing (MvPolynomial τ l)) =
      weightOneFractionMap g e x := rfl

/-- The zero-image-weight field map is reduction of the ring map. -/
@[simp] theorem weightOneZeroResidueMap_apply (g : k →+* l) (e : σ ↪ τ)
    (T : Set τ) (h : ∀ j : σ, e j ∉ T) (t : T)
    (x : FractionRing (MvPolynomial σ k)) :
    weightOneZeroResidueMap g e T h t x =
      IsLocalRing.residue _ (weightOneZeroValuationRingMap g e T h t x) := rfl

/-- The map from the source function field into target residue is injective. -/
theorem weightOneZeroResidueMap_injective (g : k →+* l) (e : σ ↪ τ)
    (T : Set τ) (h : ∀ j : σ, e j ∉ T) (t : T) :
    Function.Injective (weightOneZeroResidueMap g e T h t) :=
  (weightOneZeroResidueMap g e T h t).injective

/-- Each source variable maps to an unweighted target coefficient variable. -/
def weightOneZeroCoefficientEmbedding (e : σ ↪ τ) (T : Set τ)
    (h : ∀ j : σ, e j ∉ T) (t : T) :
    σ ↪ WeightOneCoefficientVariables T t where
  toFun j := Sum.inl ⟨e j, h j⟩
  inj' := by
    intro a b hab
    exact e.injective (congrArg Subtype.val (Sum.inl.inj hab))

/-- A source index maps to an unweighted coefficient index. -/
@[simp] theorem weightOneZeroCoefficientEmbedding_apply (e : σ ↪ τ) (T : Set τ)
    (h : ∀ j : σ, e j ∉ T) (t : T) (j : σ) :
    weightOneZeroCoefficientEmbedding e T h t j = Sum.inl ⟨e j, h j⟩ := rfl

/-- The rational-function map into target coefficient coordinates when all
image variables are unweighted. -/
noncomputable def weightOneZeroCoefficientFieldMap (g : k →+* l) (e : σ ↪ τ)
    (T : Set τ) (h : ∀ j : σ, e j ∉ T) (t : T) :
    FractionRing (MvPolynomial σ k) →+* WeightOneCoefficientField l T t :=
  weightOneFractionMap g (weightOneZeroCoefficientEmbedding e T h t)

/-- The all-unweighted-image coefficient map acts on field constants by `g`. -/
@[simp] theorem weightOneZeroCoefficientFieldMap_C (g : k →+* l) (e : σ ↪ τ)
    (T : Set τ) (h : ∀ j : σ, e j ∉ T) (t : T) (a : k) :
    weightOneZeroCoefficientFieldMap g e T h t
      (algebraMap (MvPolynomial σ k) (FractionRing (MvPolynomial σ k)) (C a)) =
      algebraMap (MvPolynomial (WeightOneCoefficientVariables T t) l)
        (WeightOneCoefficientField l T t) (C (g a)) := by
  simp [weightOneZeroCoefficientFieldMap]

private theorem weightOneZeroValuationRingMap_C (g : k →+* l) (e : σ ↪ τ)
    (T : Set τ) (h : ∀ j : σ, e j ∉ T) (t : T) (a : k) :
    weightOneZeroValuationRingMap g e T h t
      (algebraMap (MvPolynomial σ k) (FractionRing (MvPolynomial σ k)) (C a)) =
    weightOneCoefficientSection T t
      (algebraMap (MvPolynomial (WeightOneCoefficientVariables T t) l)
        (WeightOneCoefficientField l T t) (C (g a))) := by
  apply Subtype.ext
  rw [weightOneZeroValuationRingMap_val, weightOneFractionMap_polynomial,
    weightOnePolynomialMap_C, weightOneCoefficientSection_C_val]

private theorem weightOneZeroValuationRingMap_X (g : k →+* l) (e : σ ↪ τ)
    (T : Set τ) (h : ∀ j : σ, e j ∉ T) (t : T) (j : σ) :
    weightOneZeroValuationRingMap g e T h t
      (algebraMap (MvPolynomial σ k) (FractionRing (MvPolynomial σ k)) (X j)) =
    weightOneCoefficientSection T t
      (algebraMap (MvPolynomial (WeightOneCoefficientVariables T t) l)
        (WeightOneCoefficientField l T t) (X (Sum.inl (⟨e j, h j⟩ : {j : τ // j ∉ T})))) := by
  apply Subtype.ext
  rw [weightOneZeroValuationRingMap_val, weightOneFractionMap_polynomial,
    weightOnePolynomialMap_X, weightOneCoefficientSection_unweighted_val]

/-- Under the full-residue equivalence the all-unweighted-image map is the
explicit coefficient-field map on the entire source field. -/
theorem weightOneZeroResidueMap_coordinates (g : k →+* l) (e : σ ↪ τ)
    (T : Set τ) (h : ∀ j : σ, e j ∉ T) (t : T)
    (x : FractionRing (MvPolynomial σ k)) :
    weightOneResidueEquiv T t (weightOneZeroResidueMap g e T h t x) =
      weightOneZeroCoefficientFieldMap g e T h t x := by
  let left : FractionRing (MvPolynomial σ k) →+* WeightOneCoefficientField l T t :=
    (weightOneResidueEquiv T t).toRingHom.comp (weightOneZeroResidueMap g e T h t)
  have hfield : left = weightOneZeroCoefficientFieldMap g e T h t := by
    apply IsFractionRing.ringHom_ext (A := MvPolynomial σ k)
    intro p
    have hpoly : left.comp (algebraMap (MvPolynomial σ k)
        (FractionRing (MvPolynomial σ k))) =
        (weightOneZeroCoefficientFieldMap g e T h t).comp
          (algebraMap (MvPolynomial σ k) (FractionRing (MvPolynomial σ k))) := by
      apply MvPolynomial.ringHom_ext
      · intro a
        change weightOneResidueEquiv T t
          (weightOneZeroResidueMap g e T h t
            (algebraMap (MvPolynomial σ k) (FractionRing (MvPolynomial σ k)) (C a))) =
            weightOneZeroCoefficientFieldMap g e T h t
              (algebraMap (MvPolynomial σ k) (FractionRing (MvPolynomial σ k)) (C a))
        rw [weightOneZeroResidueMap_apply, weightOneZeroValuationRingMap_C,
          weightOneResidueEquiv_section, weightOneZeroCoefficientFieldMap_C]
      · intro j
        change weightOneResidueEquiv T t
          (weightOneZeroResidueMap g e T h t
            (algebraMap (MvPolynomial σ k) (FractionRing (MvPolynomial σ k)) (X j))) =
            weightOneZeroCoefficientFieldMap g e T h t
              (algebraMap (MvPolynomial σ k) (FractionRing (MvPolynomial σ k)) (X j))
        rw [weightOneZeroResidueMap_apply, weightOneZeroValuationRingMap_X,
          weightOneResidueEquiv_section]
        simp [weightOneZeroCoefficientFieldMap]
    exact DFunLike.congr_fun hpoly p
  exact DFunLike.congr_fun hfield x

/-- A weighted ratio is outside the image of a function field whose variables
all map to unweighted target variables. -/
theorem weightOneZeroCoefficientFieldMap_ratio_not_mem_range
    (g : k →+* l) (e : σ ↪ τ) (T : Set τ)
    (h : ∀ j : σ, e j ∉ T) (t : T)
    (j : {j : τ // j ∈ T ∧ j ≠ (t : τ)}) :
    algebraMap (MvPolynomial (WeightOneCoefficientVariables T t) l)
      (WeightOneCoefficientField l T t) (X (Sum.inr j)) ∉
      Set.range (weightOneZeroCoefficientFieldMap g e T h t) := by
  classical
  let embedding := weightOneZeroCoefficientEmbedding e T h t
  let targetVariable : WeightOneCoefficientVariables T t := Sum.inr j
  have hnot : targetVariable ∉ Set.range embedding := by
    rintro ⟨a, ha⟩
    have : (Sum.inr j : WeightOneCoefficientVariables T t) = Sum.inl ⟨e a, h a⟩ :=
      ha.symm
    cases this
  have hdegree (p : MvPolynomial σ k) :
      degreeOf targetVariable (weightOnePolynomialMap g embedding p) = 0 := by
    apply Nat.eq_zero_of_le_zero
    rw [degreeOf_eq_sup]
    apply Finset.sup_le
    intro exponent hexponent
    change exponent targetVariable ≤ 0
    have hmem : exponent ∈ (Finset.image (Finsupp.mapDomain embedding)
        p.support) := by
      change exponent ∈
        (rename (R := l) (embedding : σ → WeightOneCoefficientVariables T t)
          (map g p)).support at hexponent
      rwa [support_rename_of_injective embedding.injective,
        support_map_of_injective _ g.injective] at hexponent
    obtain ⟨sourceExponent, _, heq⟩ := Finset.mem_image.mp hmem
    subst exponent
    simp only [Finsupp.mapDomain_of_notMem_range sourceExponent targetVariable hnot, le_refl]
  rintro ⟨x, hx⟩
  obtain ⟨p, q, hq, rfl⟩ := IsFractionRing.div_surjective (MvPolynomial σ k) x
  have hq' : q ≠ 0 := mem_nonZeroDivisors_iff_ne_zero.mp hq
  have hqmap : weightOnePolynomialMap g embedding q ≠ 0 := by
    simpa only [map_zero] using
      (weightOnePolynomialMap_injective g g.injective embedding).ne hq'
  have hden : algebraMap
      (MvPolynomial (WeightOneCoefficientVariables T t) l)
      (WeightOneCoefficientField l T t)
      (weightOnePolynomialMap g embedding q) ≠ 0 := by
    intro hzero
    exact hqmap (IsFractionRing.to_map_eq_zero_iff.mp hzero)
  have hfrac : algebraMap
        (MvPolynomial (WeightOneCoefficientVariables T t) l)
        (WeightOneCoefficientField l T t) (X targetVariable) =
      algebraMap (MvPolynomial (WeightOneCoefficientVariables T t) l)
        (WeightOneCoefficientField l T t) (weightOnePolynomialMap g embedding p) /
      algebraMap (MvPolynomial (WeightOneCoefficientVariables T t) l)
        (WeightOneCoefficientField l T t) (weightOnePolynomialMap g embedding q) := by
    simpa only [weightOneZeroCoefficientFieldMap, weightOneFractionMap_div] using hx.symm
  have hpoly : X targetVariable * weightOnePolynomialMap g embedding q =
      weightOnePolynomialMap g embedding p := by
    apply (FaithfulSMul.algebraMap_injective
      (MvPolynomial (WeightOneCoefficientVariables T t) l)
      (WeightOneCoefficientField l T t))
    simpa only [map_mul] using (eq_div_iff hden).mp hfrac
  have hdeg := congrArg (degreeOf targetVariable) hpoly
  rw [mul_comm, (degreeOf_mul_X_eq_degreeOf_add_one_iff _ _).mpr hqmap,
    hdegree q, hdegree p] at hdeg
  omega

/-- Zero-image-weight coefficient maps send variables to unweighted
coefficient variables of the target. -/
@[simp] theorem weightOneZeroCoefficientFieldMap_X (g : k →+* l) (e : σ ↪ τ)
    (T : Set τ) (h : ∀ j : σ, e j ∉ T) (t : T) (j : σ) :
    weightOneZeroCoefficientFieldMap g e T h t
      (algebraMap (MvPolynomial σ k) (FractionRing (MvPolynomial σ k)) (X j)) =
      algebraMap (MvPolynomial (WeightOneCoefficientVariables T t) l)
        (WeightOneCoefficientField l T t)
          (X (Sum.inl (⟨e j, h j⟩ : {j : τ // j ∉ T}))) := by
  simp [weightOneZeroCoefficientFieldMap]

end MvPolynomial
