name = "multivariate-polynomials"
version = "0.1.0"
defaultTargets = ["MultivariatePolynomials", "MultivariatePolynomialsTests"]

[leanOptions]
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
weak.linter.style.header = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "83abb3e776bdefcbc447a1e44d0debe4010039e5"

[[lean_lib]]
name = "MultivariatePolynomials"

[[lean_lib]]
name = "MultivariatePolynomialsTests"
roots = ["MultivariatePolynomialsTests.IdealOfVars", "MultivariatePolynomialsTests.Axioms", "MultivariatePolynomialsTests.LeafImport", "MultivariatePolynomialsTests.ReadmeExample", "MultivariatePolynomialsTests.HomogeneousEvaluation", "MultivariatePolynomialsTests.BlockSubstitution", "MultivariatePolynomialsTests.IteratedBlockSubstitution", "MultivariatePolynomialsTests.BlockSubstitutionLaws", "MultivariatePolynomialsTests.BlockSubstitutionDegree", "MultivariatePolynomialsTests.PolynomialCoefficientHomogeneity", "MultivariatePolynomialsTests.LinearCoefficientEvaluation", "MultivariatePolynomialsTests.LinearDivision", "MultivariatePolynomialsTests.MonicLift", "MultivariatePolynomialsTests.FirstVariableLex", "MultivariatePolynomialsTests.EvaluationIdeal"]
