/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/
module

public import MultivariatePolynomials.IdealOfVars
public import MultivariatePolynomials.HomogeneousEvaluation
public import MultivariatePolynomials.BlockSubstitution
public import MultivariatePolynomials.IteratedBlockSubstitution
public import MultivariatePolynomials.BlockSubstitutionLaws
public import MultivariatePolynomials.BlockSubstitutionDegree
public import MultivariatePolynomials.PolynomialCoefficientHomogeneity
public import MultivariatePolynomials.LinearCoefficientEvaluation
public import MultivariatePolynomials.LinearDivision
public import MultivariatePolynomials.MonicLift
public import MultivariatePolynomials.FirstVariableLex
public import MultivariatePolynomials.EvaluationIdeal
public import MultivariatePolynomials.LocalizedCoordinateQuotient
public import MultivariatePolynomials.WeightOneValuation

/-!
# Multivariate polynomials

Public aggregate import for the variable-ideal non-finite-generation theorem,
homogeneous-polynomial evaluation scaling laws, and disjoint-block polynomial
substitution and its evaluation and zero-locus laws, including exact total degree
under no-zero-divisors coefficients and finite iteration
through tuple-indexed disjoint blocks and structural laws for renaming,
associativity, units and concatenation of iteration words. Extracting a polynomial
parameter coefficient via native interchange preserves each homogeneous label.
An arbitrary coefficient-linear map commutes with evaluation at base-semiring-valued
points via the native additive coefficient map, without a multiplicativity premise.
Fixed choice-dependent linear polynomial division by a family with unit leading
coefficients gives reduced remainders and preserves every coefficient ideal.
Surjective coefficient maps admit monic multivariate-polynomial lifts that
preserve the literal leading exponent, including over the zero ring.
A nonzero scalar top coefficient of the first-variable polynomial fixes its
maximum lexicographic exponent over any commutative semiring.
The ideal generated by coordinate differences at a point is identified with
the evaluation kernel, with a membership criterion and a field-valued bridge
to the singleton vanishing ideal. Polynomial substitution contracts evaluation
kernels and coordinate-difference ideals, and carries associated prime-spectrum
points contravariantly, including field-extension-valued points.
Evaluation at zero gives an algebra equivalence for the localized
coordinate quotient by `C r * X`, with representative and fraction laws.
The subset-weight-one API describes rational-function-field valuations using
minimum polynomial order, birational coordinates and a full residue field.
Import the corresponding
`MultivariatePolynomials.IdealOfVars`,
`MultivariatePolynomials.HomogeneousEvaluation`, or
`MultivariatePolynomials.BlockSubstitution`,
`MultivariatePolynomials.IteratedBlockSubstitution` or
`MultivariatePolynomials.BlockSubstitutionLaws` or
`MultivariatePolynomials.BlockSubstitutionDegree` or
`MultivariatePolynomials.PolynomialCoefficientHomogeneity` or
`MultivariatePolynomials.LinearCoefficientEvaluation` or
`MultivariatePolynomials.LinearDivision` or
`MultivariatePolynomials.MonicLift` or
`MultivariatePolynomials.FirstVariableLex` leaf directly when only one
is needed. `MultivariatePolynomials.EvaluationIdeal` supplies the
coordinate-difference statements; `MultivariatePolynomials.LocalizedCoordinateQuotient`
supplies the localized quotient interface, and `MultivariatePolynomials.WeightOneValuation`
describes subset-weight-one valuations. Test modules are deliberately not re-exported.

## References

* See the leaf modules' `## References` sections for the sources and Mathlib
  APIs behind each result, and the repository README for bibliography.
-/
